name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # corre cada medianoche
  workflow_dispatch:     # permite lanzarlo manualmente
  push:                  # también se genera cuando haces un commit
    branches:
      - main

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generar Snake
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: NataliaBlancoAgudin
          outputs: dist/snake.svg

      - name: Deploy a rama output
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

